# Site
repository: olidroide/cv
# favicon: images/favicon.ico

# Personal info
name: Oliver Mas
title: Lead Software engineer
email: cv@olidroide.es
website: olidroide.es

# Social links
# twitter_username: olidroide
# github_username:  olidroide
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: olidroide
# linkedin_username: olidroide
# pinterest_username: jekyll
# youtube_username: olidroide
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior Full-Stack Developer with 14+ Years of Experience

  I bring over 14 years of experience as a full-stack developer, adept at applying design patterns and clean code principles to deliver high-quality,<mark><b>maintainable software</b></mark>. My expertise spans both mobile development (8+ years) using <mark><b>Android</b></mark>, backend architecture with <mark><b>Python</b></mark> (5+ years) and web frontend with <mark><b>React</b></mark> (2+ years).

  Throughout my career, I've tackled projects with <mark><b>diverse technical requirements</b></mark>. This experience has fostered my strong teamwork and leadership skills, allowing me to learn from each project and continuously improve.

  I'm passionate about staying current with the latest technologies and leverage them effectively in my work. I'm also a strong advocate for Open Source Software (OSS) and actively utilize tools like Android, Git, VSCode, and Linux distributions (Manjaro) in my daily workflow.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests software engineering some of my other interests and hobbies are:
   - Dance Bollywood 🕺
   - Play ukulele & guitar 🎸
   - Maker 🤖

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
