# Site
repository: olidroide/cv
# favicon: images/favicon.ico

# Personal info
name: Oliver Mas
title: Lead Software engineer
email: cv@olidroide.es
website: olidroide.es

# Social links
# twitter_username: olidroide
# github_username:  olidroide
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: olidroide
# linkedin_username: olidroide
# pinterest_username: jekyll
# youtube_username: olidroide
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Lead Software engineer with over 10 years of experience focused in apply design patterns and clean code.
Experience with Mobile projects with <mark><b>Android</b></mark> (8+ years) and Backend architectures with <mark><b>Python</b></mark> (3+ years) is the main skill than I'm coding on.

As well I have worked at a number of projects of <mark><b>all kinds of technical requirements</b></mark> gaining knowledge, teamwork and leadership skills taking best experiences in each one to be.

My obsession is <mark><b>stay updated</b></mark> and use last versions of everything. Also use all Software Libre than I can use in my daily work(Android, Git, Inkscape, Gimp, Manjaro, VSCode, …)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests software engineering some of my other interests and hobbies are:
   - Dance Bollywood 🕺
   - Play guitar 🎸
   - Maker 🤖

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
