# Site
repository: olidroide/cv
# favicon: images/favicon.ico

# Personal info
name: Oliver Mas
title: Lead Software engineer
email: cv@olidroide.es
website: olidroide.es

# Social links
# twitter_username: olidroide
# github_username:  olidroide
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: olidroide
# linkedin_username: olidroide
# pinterest_username: jekyll
# youtube_username: olidroide
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software engineer specialized in <mark>Android</mark> (8+ years of experience) and focused in write the best <mark>clean code</mark> and use design patterns. In the last year I'm moving to Python as my main developer skill, DevOps, and Product lead at Cheerfy Ltd.

  As well I have worked at a number of projects of <mark>all kinds of technical requirements</mark> gaining knowledge, teamwork and leadership skills taking best experiences in each one to be.

  My obsession is <mark><b>stay updated</b></mark> and use last versions of everything. Also use all <mark>Software Libre</mark> than I can use in my daily work(Android, Git, Inkscape, Gimp, Manjaro, VSCode, ...)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests software engineering some of my other interests and hobbies are:
   - Dance Bollywood 🕺
   - Play guitar 🎸
   - Maker 🤖

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
